### ISSUE TITLE
Session failed on windows worker agent

### ISSUE THREAD

**Issue by mmasdoria** [aws-deadline/deadline-cloud-worker-agent#329]
### Describe Behaviour

I've install succesfully windows worker agent on a personnal windows server VM.
The agent is well synchronised with AWS deadline cloud.
When I launch a job from my PC the job is successfully created and the worker get information about the job to proceed.
But it always fails on session start.
I've test 2 cases.
1. Run as the user agent, I get this error 
{
    "level": "ERROR",
    "ti": "🔷",
    "type": "Session",
    "subtype": "Failed",
    "session_id": "session-d56ae162a27845b1a0fe1d916d5d9f80",
    "message": "Job cannot run as WORKER_AGENT_USER. Worker Agent is running with Administrator privileges.",
    "queue_id": "queue-5f67046e5ac146459e1ae40aff3b83b0",
    "job_id": "job-4b34bc9760b94215aa11c2571e4e1495"
}

2. Run with a dedicated user (create on windows and setup on aws deadline cloud)
{
    "level": "ERROR",
    "ti": "🔷",
    "type": "Session",
    "subtype": "Failed",
    "session_id": "session-59d61d1b21514806a7eae34a1514dfa6",
    "message": "No valid credentials for NXP-3DWLOAD\\jobuser available. Credentials will be fetched again 5.0 minutes after last fetch",
    "queue_id": "queue-5f67046e5ac146459e1ae40aff3b83b0",
    "job_id": "job-10a85ca5cf36434faccad160b3fee704"
}

In both cases, it doesn't work.

### Expected Behaviour

The session should be okay and the task must be executed

### Current Behaviour

The session failed and task is never executed

### Reproduction Steps

On windows server I have installed python 3.12 and aws deadline cloud worker 0.27.1.
I start the worker with : 
deadline-worker-agent --farm-id farm-xxxxxxxxxxxxxxxxxxxx --fleet-id fleet-xxxxxxxxxxxxx --logs-dir C:\Users\puuser\demoenv-logs --persistence-dir C:\Users\puuser\demoenv-persist --profile AdministratorAccess-xxxxxxxx

On my personnal PC  (linux ubuntu), I have installed deadline cloud (pip install deadline) and configure it following this guide (https://docs.aws.amazon.com/deadline-cloud/latest/userguide/create-a-farm.html).

When I start a sample job all is working as excepted until the worker failed on session step.

### Package Version

deadline-worker-agent (0.27.1)

### Language Version

Python (3.12.3)

### Operating System

Windows server 2022 Standart

**Comment by ddneilson** [comment]
Hi there. 

For the error:
> Job cannot run as WORKER_AGENT_USER. Worker Agent is running with Administrator privileges.

This is a security control to help prevent jobs from running over-privileged by default that may not be documented come to think of it.

For the error:
> No valid credentials for NXP-3DWLOAD\jobuser available. Credentials will be fetched again 5.0 minutes after last fetch

That sounds like you've configured your Queue to use a [jobs run as user for Windows](https://docs.aws.amazon.com/deadline-cloud/latest/APIReference/API_JobRunAsUser.html#deadlinecloud-Type-JobRunAsUser-windows), with the username `jobuser`. This instructs the worker agent to run jobs as the user `jobuser` -- it does this by logging in as `jobuser` with a provided password. To use this you will have had to put the `jobuser`'s password in a Secret within SecretsManager and passed the ARN of that secret to the Queue API.  If you're seeing this, then the agent wasn't able to log in as `jobuser` using the password provided; there should be other log statements above that one that point to a reason (e.g. "[please check your password is correct](https://github.com/aws-deadline/deadline-cloud-worker-agent/blob/f2225da0d4c8e29a485901ec193532a27ce2a07e/src/deadline_worker_agent/windows/win_credentials_resolver.py#L228)")

You mention a VM. Just to make sure, have you created a local user in that VM that is called `jobuser`?

**Comment by mmasdoria** [comment]
Hi and thank for your rapid answer.
For the second point I have well create password in secretmanager. 
You're right, I find this log above in the log : 
```
 📥 API.Resp 📥 [secrets-manager:GetSecretValue](400) error={'Message': 'User: arn:aws:sts::533267371924:assumed-role/AWSDeadlineCloudFleetRole-1775113762/worker-2bd53c0381be431f94731c860f27df98 is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:eu-central-1:533267371924:secret:deadline/windows/jobuser-duFO4j because no identity-based policy allows the secretsmanager:GetSecretValue action', 'Code': 'AccessDeniedException'} params={} request_id=268be638-2f43-49e6-9d27-50502beab64a
[2024-06-07 11:15:40,435][ERROR   ] Access to secret was denied. Please ensure the resource policy for arn:aws:secretsmanager:eu-central-1:533267371924:secret:deadline/windows/jobuser-duFO4j allows access to the fleet role, and the fleet role is correctly configured
[2024-06-07 11:15:40,435][ERROR   ] Contents of secret arn:aws:secretsmanager:eu-central-1:533267371924:secret:deadline/windows/jobuser-duFO4j could not be fetched or were not valid: An error occurred (AccessDeniedException) when calling the GetSecretValue operation: User: arn:aws:sts::533267371924:assumed-role/AWSDeadlineCloudFleetRole-1775113762/worker-2bd53c0381be431f94731c860f27df98 is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:eu-central-1:533267371924:secret:deadline/windows/jobuser-duFO4j because no identity-based policy allows the secretsmanager:GetSecretValue action
[2024-06-07 11:15:40,435][ERROR   ] 🔷 Session.Failed 🔷 [session-d31a21171d3c4916bf8babcd0a170291] No valid credentials for jobuser2 available. Credentials will be fetched again 5.0 minutes after last fetch [queue-5f67046e5ac146459e1ae40aff3b83b0/job-6d9db5d435f44dbd8a8ce85e880f80a8]
```
I will try to create policy.
I keep you informed.
Best regards.

**Comment by ddneilson** [comment]
Great. What you're looking for is in the documentation here: https://docs.aws.amazon.com/deadline-cloud/latest/userguide/manage-access-windows-secrets.html#grant-access

**Comment by mmasdoria** [comment]
Hi,
It works now. worker try to execute the task.
Thanks a lot for your very appreciated help.
