### ISSUE TITLE
Bug: Deadline Worker Agent does not honor Umask Settings

### ISSUE THREAD

**Issue by bindstudio** [aws-deadline/deadline-cloud-worker-agent#380]
### Describe Behaviour

 I’m seeing that in my setup running a CMF the file written to disk is not honoring the umask settings of the deadline-worker-agent user.  I'm using a FSx shared filesystem and need the files written by the deadline user to respect the umask settings.

I have the umask set to 002.  That should produce files that are RW for owner and group (664), but files rendered on deadline cloud are written to disk as (644).

### Expected Behaviour

The Deadline worker agent should honor the umask settings in ~/.bashrc

### Current Behaviour

the deadline-worker-agent seems to have a umask of 022 set somewhere else in the OS.

### Reproduction Steps

Set umask to 002 in ~/.bashrc under the deadline-worker-agent user
Touch a new file to confirm umask is working as expected
Render file with deadline-worker-agent.
Compare permissions of file rendered against umask settings in .bashrc

### Package Version

I think the latest

### Language Version

N/A

### Operating System

Rocky 9 Linux

**Comment by ddneilson** [comment]
Hey there. Thanks for the report, and sorry for the delay.

Can you help me out with a little additional information? 

1. How is your worker agent being started? Is it by `systemd`?  Reason that I ask this is that I don't believe that systemd loads the `deadline-worker-agent` user's .bashrc when running the agent.
2. How is your job's command structured? Is the command `bash` or something else? Reason that I ask is that if the command isn't bash, then it'll inherit the agent process's environment and the non-interactive environment of `/bin/sh` (which may not be bash if `/bin/sh` isn't an alias for bash in your system)

**Comment by bindstudio** [comment]
Not 100% sure how the worker agent is being started.  I followed the instructions on CMF creation for the AWS Docs. 

I'm using the Standard Integrated Houdini Submission here, so it would be whatever that is set to.

FWIW i also have UMASK set to 002 in /etc/login.defs

**Comment by bindstudio** [comment]
I followed the instructions here

https://docs.aws.amazon.com/deadline-cloud/latest/userguide/create-a-cmf.html

**Comment by ddneilson** [comment]
Alright. Those instructions have you setting up the agent to run as a systemd service. 

You'll find that those instructions created the file `/etc/systemd/system/deadline-worker.service` that tells systemd how to start and run the worker agent. In the `[Service]` section of that file, try adding:

```
[Service]
... existing content
UMask=002
```

References:
* [Systemd configuration file for UMask](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#UMask=)

**Comment by bindstudio** [comment]
OK.  I'll give that a shot

**Comment by ddneilson** [comment]
Hey there @bindstudio . Just checking in. Did the systemd configuration file suggestion end up working for you?

**Comment by ddneilson** [comment]
Closing as stale. Please don't hesitate to reopen the ticket if you need more help.
