### ISSUE TITLE
Bug: Newer release for deadline-cloud 0.49.* ?

### ISSUE THREAD

**Issue by embassytech** [aws-deadline/deadline-cloud-worker-agent#503]
### Describe Behaviour

Hi, I just did a `pip install --upgrade` for the latest `deadline-cloud` `boto3` and the various dcc submitter projects.

Unfortunately, I was surprised to discover the latest version of this package is not compatible with all those.

`
$ pip install --upgrade deadline
...
Using cached deadline-0.49.3-py3-none-any.whl (249 kB)
Installing collected packages: deadline
  Attempting uninstall: deadline
    Found existing installation: deadline 0.48.9
    Uninstalling deadline-0.48.9:
      Successfully uninstalled deadline-0.48.9
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. 
This behaviour is the source of the following dependency conflicts.
deadline-cloud-worker-agent 0.27.4 requires deadline==0.48.*, but you have deadline 0.49.3 which is incompatible.
Successfully installed deadline-0.49.3
`
Will there be a new release of this that is shortly?

thanks.

### Expected Behaviour

the latest version of this package would upgrade in alignment with the latest deadline available.

### Current Behaviour

the latest deadline upgraded, but complained about this package
Installing this package rolls back deadline and all depended dcc packages 

### Reproduction Steps

$ pip install --upgrade deadline-cloud-worker-agent

pip install --upgrade deadline

### Package Version

deadline 0.48.9 deadline-cloud-worker-agent 0.27.4

### Language Version

Python 3.9

### Operating System

linux

**Comment by moorec-aws** [comment]
Thanks for the report @embassytech, im going to close this issue in favour of https://github.com/aws-deadline/deadline-cloud-worker-agent/issues/504.
