### ISSUE TITLE
Bug: Cannot install deadline cloud with packer. Silent Failure

### ISSUE THREAD

**Issue by queglay** [aws-deadline/deadline-cloud-worker-agent#515]
### Describe Behaviour

Hello, I'm just working on upgrading to deadline cloud and building images again with it.  I submitted this issue to thinkbox support as well.

Although I can successfully install deadline cloud interactively, if I use packer it produces a non-zero exit code with no error message.
Is it possible there are uncaught exceptions thrown by this installer?

Here is the log:
```
    amazon-ebs.amznlnx2023-rendernode-ami: ===========================================================
    amazon-ebs.amznlnx2023-rendernode-ami: |      AWS Deadline Cloud Worker Agent Installer       |
    amazon-ebs.amznlnx2023-rendernode-ami: ===========================================================
    amazon-ebs.amznlnx2023-rendernode-ami:
    amazon-ebs.amznlnx2023-rendernode-ami: Farm ID: farm-b628c618484545bb82fda6b09ec99395
    amazon-ebs.amznlnx2023-rendernode-ami: Fleet ID: fleet-1aaf65dd902e47a6b17aef4351d0ca79
    amazon-ebs.amznlnx2023-rendernode-ami: Region: **************
    amazon-ebs.amznlnx2023-rendernode-ami: Worker agent user: deployuser
    amazon-ebs.amznlnx2023-rendernode-ami: Worker agent group: deployuser
    amazon-ebs.amznlnx2023-rendernode-ami: Worker job group: jobgroup
    amazon-ebs.amznlnx2023-rendernode-ami: Scripts path: /opt/deadline/worker/bin
    amazon-ebs.amznlnx2023-rendernode-ami: Worker agent program path: /opt/deadline/worker/bin/deadline-worker-agent
    amazon-ebs.amznlnx2023-rendernode-ami: Deadline client program path: /opt/deadline/worker/bin/deadline
    amazon-ebs.amznlnx2023-rendernode-ami: Allow worker agent shutdown: yes
    amazon-ebs.amznlnx2023-rendernode-ami: Start systemd service: no
    amazon-ebs.amznlnx2023-rendernode-ami: Telemetry opt-out: no
    amazon-ebs.amznlnx2023-rendernode-ami: VFS install path: unset
    amazon-ebs.amznlnx2023-rendernode-ami: Disallow EC2 instance profile: no
==> amazon-ebs.amznlnx2023-rendernode-ami: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs.amznlnx2023-rendernode-ami: Terminating the source AWS instance...
==> amazon-ebs.amznlnx2023-rendernode-ami: Cleaning up any extra volumes...
==> amazon-ebs.amznlnx2023-rendernode-ami: No volumes to clean up, skipping
==> amazon-ebs.amznlnx2023-rendernode-ami: Deleting temporary security group...
==> amazon-ebs.amznlnx2023-rendernode-ami: Deleting temporary keypair...
Build 'amazon-ebs.amznlnx2023-rendernode-ami' errored after 4 minutes 13 seconds: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
```

And this is my example source code I’m using to install deadline.  The steps are necessarily different to the AWS docs which don't work for automation with packer.  I’m using best practices when working with pip (apart from the fact that we are usind sudo. The docs request it even though sudo should not be used with pip).
```
  provisioner "shell" {
    inline = [ # TODO get thinkbox to not be using root with pip.
      "sudo su -c \"python3.11 -m venv /opt/deadline/worker\"",
      "sudo su -c \"source /opt/deadline/worker/bin/activate && cd ~; curl -O https://bootstrap.pypa.io/get-pip.py/[\](https://bootstrap.pypa.io/get-pip.py/)"", # Install pip for py3.11
      "sudo su -c \"source /opt/deadline/worker/bin/activate && python3.11 get-pip.py\"",
      "sudo su -c \"source /opt/deadline/worker/bin/activate && python3.11 -m pip --version\"",
      "sudo su -c \"source /opt/deadline/worker/bin/activate && python3.11 -m pip install --upgrade pip\"",
      "sudo su -c \"source /opt/deadline/worker/bin/activate && python3.11 -m pip install deadline-cloud-worker-agent\"",
      "sudo su -c \"source /opt/deadline/worker/bin/activate && /opt/deadline/worker/bin/install-deadline-worker --farm-id farm-b628c618484545bb82fda6b09ec99395 --fleet-id fleet-1aaf65dd902e47a6b17aef4351d0ca79 --region ap-southeast-2 --allow-shutdown --user deployuser --group jobgroup\""
    ]
    only = [
      "amazon-ebs.rocky8-rendernode-ami",
      "amazon-ebs.amznlnx2023-rendernode-ami",
    ]
  }
```

### Expected Behaviour

If there is an exception during install we need to know what the problem is to resolve it through the log.

### Current Behaviour

No exception message is output

### Reproduction Steps

Install deadline on amazon linux 2023 using Hashicorp Packer.

### Package Version

Latest via pip?

### Language Version

Python 3.11

### Operating System

Linux

**Comment by AWS-Samuel** [comment]
Hey @queglay, thanks for the bug report and detailed information!

I noticed in the commands you provided, that there isn't a `-y` argument to the `install-deadline-worker` step. I suspect that omitting this argument is the cause of the behavior you're seeing. The `-y` argument [skips the confirmation prompt](https://github.com/aws-deadline/deadline-cloud-worker-agent/blob/ca76875b3d462d2334bab5ee1f16613ef9305c83/src/deadline_worker_agent/installer/install.sh#L89-L90) before installing the worker agent. Because it wasn't provided, the worker agent installer is trying read user input from the command line, which might lead to some undefined behavior in the Packer tool that you're using. 

If you add the `-y` argument to the `/opt/deadline/worker/bin/install-deadline-worker` command, do you still see this error?

**Comment by queglay** [comment]
Thanks so much @AWS-Samuel , of course I'm feeling pretty silly right now!   That did the trick!

**Comment by AWS-Samuel** [comment]
No problem! Glad that worked 🎉
